name: 'Execução por push'

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test